### ISSUE TITLE
Verification failed with code 401 + Uncaught Exception: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by kenjibailly** [snow-sprite/CompressApp#19]
All was working fine until I get "Verification Failed with code 401"
![image](https://user-images.githubusercontent.com/9883910/173255026-38b704e8-98a5-41ac-9239-dd22acd8e59e.png)

Then these errors started popping up:
![image](https://user-images.githubusercontent.com/9883910/173255011-ad7b9fc7-fb10-4200-8480-5b76552fa3bf.png)

This happens when trying to upload multiple at once. This used to work fine, not sure what's going on.
It's also pointing to a folder that doesn't exist. It creates a folder to put the new ones in, but it's not the same name as in the error.

**Comment by snow-sprite** [comment]
> All was working fine until I get "Verification Failed with code 401" ![image](https://user-images.githubusercontent.com/9883910/173255026-38b704e8-98a5-41ac-9239-dd22acd8e59e.png)
> 
> Then these errors started popping up: ![image](https://user-images.githubusercontent.com/9883910/173255011-ad7b9fc7-fb10-4200-8480-5b76552fa3bf.png)
> 
> This happens when trying to upload multiple at once. This used to work fine, not sure what's going on. It's also pointing to a folder that doesn't exist. It creates a folder to put the new ones in, but it's not the same name as in the error.

Maybe the TinyPNG Api key is out of date or has been used more than 500 times (each key can be used 500 times per month for free). And you can register the keys at https://tinypng.com/developers. thx.

**Comment by snow-sprite** [comment]
Maybe the TinyPNG Api key is out of date or has been used more than 500 times (each key can be used 500 times per month for free). And you can register the keys at https://tinypng.com/developers. thx.

**Comment by snow-sprite** [comment]
Get your API key: <https://tinypng.com/developers>

**Comment by snow-sprite** [comment]
Get your API key: <https://tinypng.com/developers>
